version: '3'
services:
  finedust:
    build:
      context: .
      dockerfile: Dockerfile
    image: hmin10580/finedust:1.0.0
    container_name: backend-finedust
    command: "python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/finedust
    expose:
      - "8000"